[build-system]
requires = ["poetry-core>=1.0.0", "maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "donor"
version = "0.1.0"
license = { text = "MIT" }

[tool.maturin]
python-source = "."
